[etqtesettings]
number_of_states_presented = 16
prefix_of_matrix_files = "heff2/"
suffix_of_matrix_files = ".mat"
number_of_systems = 1000
number_of_steps = 1000
step_length = 100.0
initial_state = "5620"
state_names_presented = [
  "5620",
  "5621",
  "602_1",
  "603_1",
  "604_1",
  "610_1",
  "611_1",
  "612_1",
  "613_1",
  "602_2",
  "603_2",
  "604_2",
  "610_2",
  "611_2",
  "612_2",
  "613_2",
]
write_isosys = false
